/**
 * Popular Symbols for Investment Tracking
 * 
 * Curated lists of top stocks, crypto, ETFs, and commodities
 * to help users quickly add assets without typos.
 */

export interface Symbol {
  ticker: string;
  name: string;
}

// Top 50 US Stocks (by market cap + popularity)
export const POPULAR_STOCKS: Symbol[] = [
  { ticker: 'AAPL', name: 'Apple Inc.' },
  { ticker: 'MSFT', name: 'Microsoft Corporation' },
  { ticker: 'GOOGL', name: 'Alphabet Inc. (Google)' },
  { ticker: 'AMZN', name: 'Amazon.com Inc.' },
  { ticker: 'NVDA', name: 'NVIDIA Corporation' },
  { ticker: 'META', name: 'Meta Platforms (Facebook)' },
  { ticker: 'TSLA', name: 'Tesla Inc.' },
  { ticker: 'BRK.B', name: 'Berkshire Hathaway' },
  { ticker: 'V', name: 'Visa Inc.' },
  { ticker: 'JPM', name: 'JPMorgan Chase & Co.' },
  { ticker: 'WMT', name: 'Walmart Inc.' },
  { ticker: 'MA', name: 'Mastercard Inc.' },
  { ticker: 'JNJ', name: 'Johnson & Johnson' },
  { ticker: 'PG', name: 'Procter & Gamble' },
  { ticker: 'UNH', name: 'UnitedHealth Group' },
  { ticker: 'HD', name: 'Home Depot' },
  { ticker: 'DIS', name: 'Walt Disney Company' },
  { ticker: 'BAC', name: 'Bank of America' },
  { ticker: 'NFLX', name: 'Netflix Inc.' },
  { ticker: 'CRM', name: 'Salesforce Inc.' },
  { ticker: 'ORCL', name: 'Oracle Corporation' },
  { ticker: 'ADBE', name: 'Adobe Inc.' },
  { ticker: 'KO', name: 'Coca-Cola Company' },
  { ticker: 'PEP', name: 'PepsiCo Inc.' },
  { ticker: 'COST', name: 'Costco Wholesale' },
  { ticker: 'CSCO', name: 'Cisco Systems' },
  { ticker: 'INTC', name: 'Intel Corporation' },
  { ticker: 'AMD', name: 'Advanced Micro Devices' },
  { ticker: 'PYPL', name: 'PayPal Holdings' },
  { ticker: 'NKE', name: 'Nike Inc.' },
  { ticker: 'TMO', name: 'Thermo Fisher Scientific' },
  { ticker: 'ABT', name: 'Abbott Laboratories' },
  { ticker: 'MRK', name: 'Merck & Co.' },
  { ticker: 'PFE', name: 'Pfizer Inc.' },
  { ticker: 'CVX', name: 'Chevron Corporation' },
  { ticker: 'XOM', name: 'Exxon Mobil Corporation' },
  { ticker: 'AVGO', name: 'Broadcom Inc.' },
  { ticker: 'TXN', name: 'Texas Instruments' },
  { ticker: 'QCOM', name: 'Qualcomm Inc.' },
  { ticker: 'HON', name: 'Honeywell International' },
  { ticker: 'UPS', name: 'United Parcel Service' },
  { ticker: 'BA', name: 'Boeing Company' },
  { ticker: 'GE', name: 'General Electric' },
  { ticker: 'IBM', name: 'IBM Corporation' },
  { ticker: 'CAT', name: 'Caterpillar Inc.' },
  { ticker: 'GS', name: 'Goldman Sachs Group' },
  { ticker: 'AXP', name: 'American Express' },
  { ticker: 'MMM', name: '3M Company' },
  { ticker: 'MCD', name: 'McDonald\'s Corporation' },
  { ticker: 'SBUX', name: 'Starbucks Corporation' },
];

// Top 30 Cryptocurrencies (by market cap)
export const POPULAR_CRYPTO: Symbol[] = [
  { ticker: 'BTC/USD', name: 'Bitcoin' },
  { ticker: 'ETH/USD', name: 'Ethereum' },
  { ticker: 'USDT/USD', name: 'Tether' },
  { ticker: 'BNB/USD', name: 'Binance Coin' },
  { ticker: 'SOL/USD', name: 'Solana' },
  { ticker: 'XRP/USD', name: 'Ripple' },
  { ticker: 'USDC/USD', name: 'USD Coin' },
  { ticker: 'ADA/USD', name: 'Cardano' },
  { ticker: 'AVAX/USD', name: 'Avalanche' },
  { ticker: 'DOGE/USD', name: 'Dogecoin' },
  { ticker: 'DOT/USD', name: 'Polkadot' },
  { ticker: 'MATIC/USD', name: 'Polygon' },
  { ticker: 'SHIB/USD', name: 'Shiba Inu' },
  { ticker: 'LTC/USD', name: 'Litecoin' },
  { ticker: 'TRX/USD', name: 'TRON' },
  { ticker: 'LINK/USD', name: 'Chainlink' },
  { ticker: 'UNI/USD', name: 'Uniswap' },
  { ticker: 'ATOM/USD', name: 'Cosmos' },
  { ticker: 'XLM/USD', name: 'Stellar' },
  { ticker: 'ALGO/USD', name: 'Algorand' },
  { ticker: 'VET/USD', name: 'VeChain' },
  { ticker: 'FIL/USD', name: 'Filecoin' },
  { ticker: 'HBAR/USD', name: 'Hedera' },
  { ticker: 'APT/USD', name: 'Aptos' },
  { ticker: 'NEAR/USD', name: 'NEAR Protocol' },
  { ticker: 'ICP/USD', name: 'Internet Computer' },
  { ticker: 'ARB/USD', name: 'Arbitrum' },
  { ticker: 'OP/USD', name: 'Optimism' },
  { ticker: 'INJ/USD', name: 'Injective' },
  { ticker: 'SUI/USD', name: 'Sui' },
];

// Top 30 ETFs (most popular + diversified)
export const POPULAR_ETFS: Symbol[] = [
  { ticker: 'SPY', name: 'SPDR S&P 500 ETF' },
  { ticker: 'VOO', name: 'Vanguard S&P 500 ETF' },
  { ticker: 'IVV', name: 'iShares Core S&P 500 ETF' },
  { ticker: 'QQQ', name: 'Invesco QQQ (Nasdaq-100)' },
  { ticker: 'VTI', name: 'Vanguard Total Stock Market' },
  { ticker: 'VEA', name: 'Vanguard FTSE Developed Markets' },
  { ticker: 'VWO', name: 'Vanguard FTSE Emerging Markets' },
  { ticker: 'AGG', name: 'iShares Core US Aggregate Bond' },
  { ticker: 'BND', name: 'Vanguard Total Bond Market' },
  { ticker: 'GLD', name: 'SPDR Gold Shares' },
  { ticker: 'SLV', name: 'iShares Silver Trust' },
  { ticker: 'VNQ', name: 'Vanguard Real Estate ETF' },
  { ticker: 'VIG', name: 'Vanguard Dividend Appreciation' },
  { ticker: 'SCHD', name: 'Schwab US Dividend Equity' },
  { ticker: 'VYM', name: 'Vanguard High Dividend Yield' },
  { ticker: 'DIA', name: 'SPDR Dow Jones Industrial Average' },
  { ticker: 'IWM', name: 'iShares Russell 2000 (Small Cap)' },
  { ticker: 'EFA', name: 'iShares MSCI EAFE' },
  { ticker: 'EEM', name: 'iShares MSCI Emerging Markets' },
  { ticker: 'TLT', name: 'iShares 20+ Year Treasury Bond' },
  { ticker: 'LQD', name: 'iShares iBoxx Investment Grade Corporate' },
  { ticker: 'HYG', name: 'iShares iBoxx High Yield Corporate' },
  { ticker: 'XLF', name: 'Financial Select Sector SPDR' },
  { ticker: 'XLK', name: 'Technology Select Sector SPDR' },
  { ticker: 'XLE', name: 'Energy Select Sector SPDR' },
  { ticker: 'XLV', name: 'Health Care Select Sector SPDR' },
  { ticker: 'XLI', name: 'Industrial Select Sector SPDR' },
  { ticker: 'XLP', name: 'Consumer Staples Select Sector' },
  { ticker: 'XLY', name: 'Consumer Discretionary Select Sector' },
  { ticker: 'ARKK', name: 'ARK Innovation ETF' },
];

// Top 20 Commodities
export const POPULAR_COMMODITIES: Symbol[] = [
  { ticker: 'GOLD', name: 'Gold' },
  { ticker: 'SILVER', name: 'Silver' },
  { ticker: 'PLATINUM', name: 'Platinum' },
  { ticker: 'PALLADIUM', name: 'Palladium' },
  { ticker: 'COPPER', name: 'Copper' },
  { ticker: 'WTI/USD', name: 'Crude Oil (WTI)' },
  { ticker: 'BRENT/USD', name: 'Crude Oil (Brent)' },
  { ticker: 'NATGAS', name: 'Natural Gas' },
  { ticker: 'WHEAT', name: 'Wheat' },
  { ticker: 'CORN', name: 'Corn' },
  { ticker: 'SOYBEAN', name: 'Soybeans' },
  { ticker: 'SUGAR', name: 'Sugar' },
  { ticker: 'COFFEE', name: 'Coffee' },
  { ticker: 'COTTON', name: 'Cotton' },
  { ticker: 'COCOA', name: 'Cocoa' },
  { ticker: 'ALUMINUM', name: 'Aluminum' },
  { ticker: 'ZINC', name: 'Zinc' },
  { ticker: 'NICKEL', name: 'Nickel' },
  { ticker: 'LUMBER', name: 'Lumber' },
  { ticker: 'URANIUM', name: 'Uranium' },
];
